server:
  port: 9001

spring:
  application:
    name: nacos-provider-payment9001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudAlibaba?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr:  39.104.205.172:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'
