server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment9001
  cloud:
    nacos:
      discovery:
        server-addr:  39.104.205.172:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'
